server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: Reservation
          uri: http://localhost:8082
          predicates:
            - Path=/reservations/**, 
        - id: Customer
          uri: http://localhost:8083
          predicates:
            - Path=/customers/**,
        - id: Notification
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**,
        - id: Admin
          uri: http://localhost:8085
          predicates:
            - Path=/admins/**,
        - id: Airplane
          uri: http://localhost:8086
          predicates:
            - Path=/airplanes/**,
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/**, 
        - id: Customer
          uri: http://customer:8080
          predicates:
            - Path=, 
        - id: Notification
          uri: http://notification:8080
          predicates:
            - Path=, 
        - id: Admin
          uri: http://admin:8080
          predicates:
            - Path=, 
        - id: Airplane
          uri: http://airplane:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
