server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: Insurance
          uri: http://localhost:8082
          predicates:
            - Path=/insurances/**, 
        - id: Member
          uri: http://localhost:8083
          predicates:
            - Path=/members/**, 
        - id: Review
          uri: http://localhost:8084
          predicates:
            - Path=/reviews/**, 
        - id: Notification
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**, 
        - id: MyPage
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Insurance
          uri: http://insurance:8080
          predicates:
            - Path=/insurances/**, 
        - id: Member
          uri: http://member:8080
          predicates:
            - Path=/members/**, 
        - id: Review
          uri: http://review:8080
          predicates:
            - Path=/reviews/**, 
        - id: Notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**, 
        - id: MyPage
          uri: http://myPage:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
