---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 보험
  labels:
    app: 보험
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 보험
  template:
    metadata:
      labels:
        app: 보험
    spec:
      containers:
        - name: 보험
          image: username/보험:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 회원
  labels:
    app: 회원
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 회원
  template:
    metadata:
      labels:
        app: 회원
    spec:
      containers:
        - name: 회원
          image: username/회원:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 심사
  labels:
    app: 심사
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 심사
  template:
    metadata:
      labels:
        app: 심사
    spec:
      containers:
        - name: 심사
          image: username/심사:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: 보험
  labels:
    app: 보험
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 보험


---


apiVersion: v1
kind: Service
metadata:
  name: 회원
  labels:
    app: 회원
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 회원


---


apiVersion: v1
kind: Service
metadata:
  name: 심사
  labels:
    app: 심사
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 심사

