---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Insurance
  labels:
    app: Insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Insurance
  template:
    metadata:
      labels:
        app: Insurance
    spec:
      containers:
        - name: Insurance
          image: username/Insurance:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Member
  labels:
    app: Member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Member
  template:
    metadata:
      labels:
        app: Member
    spec:
      containers:
        - name: Member
          image: username/Member:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Review
  labels:
    app: Review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Review
  template:
    metadata:
      labels:
        app: Review
    spec:
      containers:
        - name: Review
          image: username/Review:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Insurance
  labels:
    app: Insurance
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Insurance


---


apiVersion: v1
kind: Service
metadata:
  name: Member
  labels:
    app: Member
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Member


---


apiVersion: v1
kind: Service
metadata:
  name: Review
  labels:
    app: Review
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Review

