---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Reservation
  labels:
    app: Reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Reservation
  template:
    metadata:
      labels:
        app: Reservation
    spec:
      containers:
        - name: Reservation
          image: username/Reservation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Customer
  labels:
    app: Customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Customer
  template:
    metadata:
      labels:
        app: Customer
    spec:
      containers:
        - name: Customer
          image: username/Customer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Notification
  labels:
    app: Notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Notification
  template:
    metadata:
      labels:
        app: Notification
    spec:
      containers:
        - name: Notification
          image: username/Notification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Admin
  labels:
    app: Admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Admin
  template:
    metadata:
      labels:
        app: Admin
    spec:
      containers:
        - name: Admin
          image: username/Admin:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Airplane
  labels:
    app: Airplane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Airplane
  template:
    metadata:
      labels:
        app: Airplane
    spec:
      containers:
        - name: Airplane
          image: username/Airplane:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Reservation
  labels:
    app: Reservation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Reservation


---


apiVersion: v1
kind: Service
metadata:
  name: Customer
  labels:
    app: Customer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Customer


---


apiVersion: v1
kind: Service
metadata:
  name: Notification
  labels:
    app: Notification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Notification


---


apiVersion: v1
kind: Service
metadata:
  name: Admin
  labels:
    app: Admin
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Admin


---


apiVersion: v1
kind: Service
metadata:
  name: Airplane
  labels:
    app: Airplane
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Airplane

